version: "3"

x-arg: &version
  args:
    - HADOOP_VERSION=2.7.7
    - HADOOP_MAJOR_VERSION=2.7
    - SPARK_VERSION=2.4.8
    - HIVE_VERSION=2.3.9

x-service: &service
  env_file:
    - ./hadoop.env

services:
  namenode:
    <<: *service
    build:
      context: ./base
      dockerfile: Dockerfile
      target: namenode
      <<: *version
    container_name: hadoop_namenode
    ports:
      - 19870:9870
      - 19000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test

  datanode:
    <<: *service
    build: 
      context: ./base
      dockerfile: Dockerfile
      target: datanode
      <<: *version
    container_name: hadoop_datanode
    ports:
      - 19864:9864
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
  
  resourcemanager:
    <<: *service
    build: 
      context: ./base
      dockerfile: Dockerfile
      target: resourcemanager
      <<: *version
    container_name: hadoop_resourcemanager
    ports:
      - 18088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
  
  nodemanager:
    <<: *service
    build: 
      context: ./base
      dockerfile: Dockerfile
      target: nodemanager
      <<: *version
    container_name: hadoop_nodemanager
    ports:
      - 18042:8042
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
      
  historyserver:
    <<: *service
    build: 
      context: ./base
      dockerfile: Dockerfile
      target: historyserver
      <<: *version
    container_name: hadoop_historyserver
    ports:
      - 18188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
  
  console:
    <<: *service
    build: 
      context: ./base
      dockerfile: Dockerfile
      target: console
      <<: *version
    container_name: hadoop_console
    volumes:
      - ${LOCAL_DEV_DIR}:/work
    ports:
      - 4040:4040

volumes:
    hadoop_namenode:
    hadoop_datanode:
    hadoop_historyserver:
