version: "3"

x-arg: &version
  args:
    - HADOOP_VERSION=2.7.7
    - HADOOP_MAJOR_VERSION=2.7
    - SPARK_VERSION=2.4.8
    - HIVE_VERSION=2.3.9

x-service: &service
  env_file:
    - ./hadoop.env

services:
  namenode:
    <<: *service
    build:
      context: ./base
      dockerfile: Dockerfile
      target: namenode
      <<: *version
    container_name: hadoop_namenode
    ports:
      - 9000:9000
      - 9870:9870   # hadoop 3
      - 50070:50070 # hadoop 2
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test

  datanode:
    <<: *service
    build: 
      context: ./base
      dockerfile: Dockerfile
      target: datanode
      <<: *version
    container_name: hadoop_datanode
    ports:
      - 9864:9864 # Hadoop 3
      - 50075:50075 # Hadoop 2
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      # SERVICE_PRECONDITION: "namenode:9870" # hadoop3
      SERVICE_PRECONDITION: "namenode:50070" # hadoop2
  
  resourcemanager:
    <<: *service
    build: 
      context: ./base
      dockerfile: Dockerfile
      target: resourcemanager
      <<: *version
    container_name: hadoop_resourcemanager
    ports:
      - 8088:8088
    environment:
      # SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864" # Hadoop 3
      SERVICE_PRECONDITION: "namenode:9000 namenode:50070 datanode:50075"
  
  nodemanager:
    <<: *service
    build: 
      context: ./base
      dockerfile: Dockerfile
      target: nodemanager
      <<: *version
    container_name: hadoop_nodemanager
    ports:
      - 8042:8042
    environment:
      # SERVICE_PRECONDITION: "namenode:9000 datanode:9864 resourcemanager:8088" # Hadoop 3
      SERVICE_PRECONDITION: "namenode:9000 datanode:50075 resourcemanager:8088" # Hadoop 2
      
  historyserver:
    <<: *service
    build: 
      context: ./base
      dockerfile: Dockerfile
      target: historyserver
      <<: *version
    container_name: hadoop_historyserver
    ports:
      - 8188:8188
    environment:
      # SERVICE_PRECONDITION: "namenode:9000 datanode:9864 resourcemanager:8088" # Hadoop 3
      SERVICE_PRECONDITION: "namenode:9000 datanode:50075 resourcemanager:8088" # Hadoop 2
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
  
  console:
    <<: *service
    build: 
      context: ./base
      dockerfile: Dockerfile
      target: console
      <<: *version
    container_name: hadoop_console
    volumes:
      - ${LOCAL_DEV_DIR}:/work
    ports:
      - 4040:4040

volumes:
    hadoop_namenode:
    hadoop_datanode:
    hadoop_historyserver:
